# LLM Provider Configuration
# Available options: 'openai', 'ollama', 'groq', 'anthropic'

llm_provider: 'openai'

# LLM Model Name
# refer to groq or openai documentation for available models
# llm_model_name: 'llama-3.2-90b-text-preview'
llm_model_name: 'gpt-4o-mini'
# llm_model_name: 'claude-3-5-sonnet-latest'

# LLM Parameters (optional - adjust as needed)
# llm_parameters:
#   temperature: 0.2
#   request_timeout: 220.0

# Embedding Provider Configuration
# Available options: 'huggingface' (for Groq & Ollama), 'default' (for OpenAI and Anthropic)
# embedding_provider: 'huggingface'
embedding_provider: 'default'

# Embedding Model Name (comment for OpenAI/Anthropic, uncomment if using Hugging Face)
# embedding_name: 'mixedbread-ai/mxbai-embed-large-v1'

# API Keys
# set them at system level
# see : https://chatgpt.com/share/6715773a-ca24-800e-a80c-109fd28dce35
api_keys:
  openai_api_key: '${OPENAI_API_KEY}'
  groq_api_key: '${GROQ_API_KEY}'
  anthropic_api_key: '${ANTHROPIC_API_KEY}'
  # if needed
  # ollama_api_key: '${OLLAMA_API_KEY}'
